import type { FailureCode } from "./webSearchTypes";

export const DEFAULT_SEARXNG_INSTANCES = [
  "https://noogle.maniworld31.com",
  "https://searxng.lmdr.io",
  "https://search.volmute.com",
  "https://google.thejot.org",
  "https://search.negrete.me",
  "https://ddg.thejot.org",
  "https://seachx.lunarfire.home64.de",
  "https://search.0x7c0.com",
  "https://rohsearch.com",
  "https://searxng.asudox.dev",
  "https://search.thejot.org",
  "https://sousuo.emoe.top",
  "https://searxng.tobe2d.dscloud.me",
  "https://searx.voe.chainsawgaming.de",
  "https://so.houhoukang.com",
  "https://searxng-pilot.jitera.app",
  "https://search.krige.nl",
  "https://search.stryder.cc",
  "https://search.corrently.cloud",
  "https://searx.thejot.org",
  "https://searxng.josephzulick.com",
  "https://search.mixel.cloud",
  "https://searxng.ctrl.corpgroup.site",
  "https://search.skyday.eu",
  "https://search.privatevoid.net",
  "https://searxng.urbanbear.dev",
  "https://search.muellers-software.org",
  "https://search.csotopare.us",
  "https://search.jbtec.eu",
  "https://search.no-code.gdn",
  "https://www.correns.co",
  "https://search.die-blahuts.de",
  "https://searxng.vyro.ai",
  "https://searxng.sbbz-ilvesheim.de",
  "https://search.jakespeed.org",
  "https://searxng.pietro.in",
  "https://search.chgr.cc",
  "https://search.eximias.ch",
  "https://negativenull.com",
  "https://searx.privhub.space",
  "https://seek.nuer.cc",
  "https://search.lucathomas.de",
  "https://search.hirad.it",
  "https://search.notashelf.dev",
];

export const CLIENT_REQUEST_TIMEOUT_MS = 7_000;

export const COOLDOWN_BY_FAILURE: Record<FailureCode, number> = {
  rate_limited: 8 * 60 * 1000,
  format_blocked: 15 * 60 * 1000,
  anti_bot: 10 * 60 * 1000,
  timeout: 3 * 60 * 1000,
  network: 2 * 60 * 1000,
  invalid_json: 4 * 60 * 1000,
  http_error: 3 * 60 * 1000,
  unknown: 2 * 60 * 1000,
};
